import Head from 'next/head'
import GalleryImage from './galleryImage';
import One from '../../public/galleryImages/1.jpeg'
import two from '../../public/galleryImages/2.jpeg'
import three from '../../public/galleryImages/3.jpeg'
import four from '../../public/galleryImages/4.jpeg'
import five from '../../public/galleryImages/5.jpeg'
import six from '../../public/galleryImages/6.jpeg'
import styles from '@/styles/Courses.module.css'
import { useState } from 'react';
import Gallery1 from './gallery1';
import Gallery2 from './gallery2';




const Gallery = () => {
    const [showGallery1, setshowGallery1] = useState(false)
    const [showGallery2, setshowGallery2] = useState(false)
    return (
        <>
            <Head>
                <title>Origin Institute</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <div className='container'>
                <section className="py-5">
                    <div className="container my-5">
                        <div className="text-center mb-5">
                            <h2 className="display-5 fw-bolder"><span className="text-gradient d-inline">Gallery of Unforgettable Moments</span></h2>
                            <p className="lead fw-light mb-4">Capturing the essence of our journey, one cherished memory at a time.</p>
                        </div>
                        <div className="row gx-2 d-flex justify-content-center">
                            <GalleryImage image={One} />
                            <GalleryImage image={two} />
                            <GalleryImage image={three} />
                            <GalleryImage image={four} />
                            <GalleryImage image={five} />
                            <GalleryImage image={six} />
                            {showGallery1 && <Gallery1 />}
                            {showGallery2 && <Gallery2 />}
                        </div>
                        {!showGallery1 && <div className='text-center mt-5'>
                            <button onClick={() => setshowGallery1(true)} className={`${styles.buttons}`} > Load More</button>
                        </div>}
                        {showGallery1 && !showGallery2 &&<div className='text-center mt-5'>
                            <button onClick={() => setshowGallery2(true)} className={`${styles.buttons}`} > Load More</button>
                        </div>}
                    </div>
                </section >
            </div >
        </>
    )
}

export default Gallery;