import Head from 'next/head'
import Link from 'next/link';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { library } from "@fortawesome/fontawesome-svg-core";
import { faGears, faSuperscript, faFlaskVial, faHandPointRight, faBuildingColumns, faUserGraduate, faStethoscope } from "@fortawesome/free-solid-svg-icons";


library.add(faGears, faSuperscript, faFlaskVial, faHandPointRight, faBuildingColumns, faUserGraduate, faStethoscope);
import styles from '@/styles/Courses.module.css'

const Courses = () => {
    return (
        <>
            <Head>
                <title>Origin Institute</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <div className={styles.memberships}>
                <h1 className={styles.animateMembership}>Our Course Specialization</h1>
                <p className={`${styles.membership_description} animateMembership`}>Proven results, experienced faculty, tailored approaches for effective learning and exam success.</p>
                <div className={`${styles.membership_wrapper} mb-5`}>
                    <div className={`${styles.membership_card} animateCard  `}>
                        <div className={`${styles.membership_title}`}>
                            <FontAwesomeIcon icon={faBuildingColumns} className={styles.card_icon} />
                            <h3>IIT-JEE</h3>
                        </div>
                        <div className={`${styles.membershop_perks}`}>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Undergraduate engineering entrance exam in India.</p>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Conducted by NTA for admission to NITs, IIITs.</p>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Highly competitive and challenging exam.</p>
                        </div>
                        <Link href="/detailiit" className={`${styles.buttons}`}>Know More</Link>
                    </div>

                    <div className={`${styles.membership_card} animateCard  `}>
                        <div className={`${styles.membership_title}`}>
                            <FontAwesomeIcon icon={faUserGraduate} className={styles.card_icon} />
                            <h3>MHT-CET</h3>
                        </div>
                        <div className={`${styles.membershop_perks}`}>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Maharashtra state-level entrance exam for various courses.</p>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Includes engineering, pharmacy, and agriculture courses.</p>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Develops analytical thinking, essential for engineering entrance.</p>
                        </div>
                        <Link href="/detailcet" className={`${styles.buttons}`}>Know More</Link>
                    </div>

                    <div className={`${styles.membership_card} animateCard  `}>
                        <div className={`${styles.membership_title}`}>
                            <FontAwesomeIcon icon={faStethoscope} className={styles.card_icon} />
                            <h3>NEET</h3>
                        </div>
                        <div className={`${styles.membershop_perks}`}>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Medical entrance exam in India for MBBS/BDS.</p>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Replaced various state-level medical entrance tests.</p>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Conducted by NTA for admission to medical colleges.</p>
                        </div>
                        <Link href="/detailneet" className={`${styles.buttons}`}>Know More</Link>
                    </div>


                </div>

                <h1 className={styles.animateMembership}>Our Expertise Subjects</h1>
                <p className={`${styles.membership_description} animateMembership`}>Backed by tangible outcomes, seasoned educators, and customized strategies for successful learning.</p>
                <div className={styles.membership_wrapper}>
                    <div className={`${styles.membership_card} animateCard  `}>
                        <div className={`${styles.membership_title}`}>
                            <FontAwesomeIcon icon={faGears} className={styles.card_icon} />
                            <h3>Physics</h3>
                        </div>
                        <div className={`${styles.membershop_perks}`}>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Laws of nature, motion, energy, forces, waves, particles.</p>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Mechanics, electromagnetism, optics, modern physics.</p>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Problem-solving skills honed for engineering challenges</p>
                        </div>
                        <Link href="https://wa.me/7776969462?text=Hi%20there,%20I%20want%20to%20know%20more%20about%20individual%20Physics%20course%20" target="_blank"
                            rel="noopener noreferrer"
                            className={`${styles.buttons}`}>Know More</Link>
                    </div>

                    <div className={`${styles.membership_card} animateCard  `}>
                        <div className={`${styles.membership_title}`}>
                            <FontAwesomeIcon icon={faSuperscript} className={styles.card_icon} />
                            <h3>Mathematics</h3>
                        </div>
                        <div className={`${styles.membershop_perks}`}>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Advanced concepts in calculus, algebra, geometry.</p>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Problem-solving, Permutations & Combinations, logic is crucial.</p>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Develops analytical thinking, essential for engineering entrance.</p>
                        </div>
                        <Link href="https://wa.me/7776969462?text=Hi%20there,%20I%20want%20to%20know%20more%20about%20individual%20Mathematics%20course%20" target="_blank"
                            rel="noopener noreferrer"
                            className={`${styles.buttons}`}>Know More</Link>
                    </div>

                    <div className={`${styles.membership_card} animateCard  `}>
                        <div className={`${styles.membership_title}`}>
                            <FontAwesomeIcon icon={faFlaskVial} className={styles.card_icon} />
                            <h3>Chemistry</h3>
                        </div>
                        <div className={`${styles.membershop_perks}`}>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Concepts in atoms, molecules, reactions, bonds, and states</p>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Explores matter&apos;s structure, composition, and transformations.</p>
                            <p><FontAwesomeIcon icon={faHandPointRight} className='me-2' />Focus on physical, organic, and inorganic chemistry fundamentals.</p>
                        </div>
                        <Link href="https://wa.me/7776969462?text=Hi%20there,%20I%20want%20to%20know%20more%20about%20individual%20Chemistry%20course%20" target="_blank"
                            rel="noopener noreferrer"
                            className={`${styles.buttons}`}>Know More</Link>
                    </div>


                </div>
            </div >
        </>
    )
}

export default Courses