import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'
import PavanJImg from '../public/studentImages/pawanj.png'
import ManasImg from '../public/studentImages/manas.png'
import PawanImg from '../public/studentImages/pawan.png'
import DevyaniImg from '../public/studentImages/devyani.png'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { library } from "@fortawesome/fontawesome-svg-core";
import { faPhone, faCommentDots } from "@fortawesome/free-solid-svg-icons";

import styles from '@/styles/Detail.module.css'

library.add(faPhone, faCommentDots);
const Detailcet = () => {
  return (
    <>
      <Head>
        <title>Origin Institute</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={styles.detailsPage}>
        <section className={styles.topResult}>
          <div className="container px-5 my-5 pt-3">
            <div className="text-center">
              <h2 className="fw-bolder">Top Results</h2>
              <p className="lead fw-normal text-muted mb-5">Dedicated to quality and your success</p>
            </div>
            <div className="row gx-5 row-cols-1 row-cols-sm-2 row-cols-xl-4 justify-content-center">
              <div className="col mb-5 mb-5 mb-xl-0">
                <div className="text-center">
                  <Image className="img-fluid rounded-circle mb-4 px-4" src={PavanJImg} alt="..." />
                  <h5 className="fw-bolder">Pawan Jadhao</h5>
                  <div className="fst-italic  ">COEP Pune</div>
                </div>
              </div>
              <div className="col mb-5 mb-5 mb-xl-0">
                <div className="text-center">
                  <Image className="img-fluid rounded-circle mb-4 px-4" src={ManasImg} alt="..." />
                  <h5 className="fw-bolder">Manas Rathi</h5>
                  <div className="fst-italic  ">PICT Pune</div>
                </div>
              </div>
              <div className="col mb-5 mb-5 mb-sm-0">
                <div className="text-center">
                  <Image className="img-fluid rounded-circle mb-4 px-4" src={PawanImg} alt="..." />
                  <h5 className="fw-bolder">Pawan Jadhao</h5>
                  <div className="fst-italic  ">DJ Sanghvi</div>
                </div>
              </div>
              <div className="col mb-5">
                <div className="text-center">
                  <Image className="img-fluid rounded-circle mb-4 px-4" src={DevyaniImg} alt="..." />
                  <h5 className="fw-bolder">Devyani Thokal</h5>
                  <div className="fst-italic  ">VIT Pune</div>
                </div>
              </div>
            </div>
          </div>
        </section>


        <section class="py-5" id={styles.content}>
          <div class="container px-5 my-5">
            <div class="row gx-5">
              <div class="col-lg-3">
                <div class="d-flex align-items-center mt-lg-5 mb-4">

                  <div class="ms-3">
                    <div class="fw-bold">Valerie Luna</div>
                    <div class="text-muted">News, Business</div>
                  </div>
                </div>
              </div>
              <div class="col-lg-9">

                <article>

                  <header class="mb-4">

                    <h1 class="fw-bolder mb-1">MHT-CET</h1>

                    <div class="text-muted fst-italic mb-2">January 1, 2021</div>

                    <a class="badge bg-primary text-decoration-none link-light me-1" href="#!">Web Design</a>
                    <a class="badge bg-primary text-decoration-none link-light" href="#!">Freebies</a>
                  </header>

                  <section class="mb-5">
                    <p class="fs-5 mb-4">MHT CET (or Maharashtra Common Entrance Test) is a common state level entrance exam conducted by the State Common Entrance Test Cell, Government of Maharashtra every year for admission to undergraduate engineering, pharmacy and agriculture courses such as B.Tech/ B.E, Pharma D and B.Pharma offered at colleges in Maharashtra.</p>
                    <p class="fs-5 mb-4">The examination is be conducted at various centres across the Maharashtra as well as outside Maharashtra State by Online mode (Computer Based Test) for PCM and PCB group separately.</p>
                    <h2 class="fw-bolder mb-4 mt-5">Paper Pattern</h2>
                    <p class="fs-5 mb-4">The paper pattern consits of be two sections in the exam - Physics, Chemistry, and Mathematics. Each section of the MHT CET  question paper will carry 100 marks. </p>
                    <p class="fs-5 mb-4">The MHT CET question paper 2024 will be prepared on the basis of the Class 11th and 12th syllabus of the Maharashtra State Board of Secondary and Higher Secondary Education.</p>
                  </section>
                </article>
                <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xxl-start mb-3">
                  <Link class="btn btn-primary btn-lg px-5 py-3 me-sm-3 fs-6 fw-bolder" href="tel:7776969462"><FontAwesomeIcon icon={faPhone} shake className='me-2' />Call US</Link>
                  <Link class="btn btn-primary btn-lg px-5 py-3 fs-6 fw-bolder" href="https://wa.me/7776969462?text=Hi%20there,%20I%20want%20to%20know%20more%20about%20MHT-CET%20course%20" target="_blank"
                    rel="noopener noreferrer"><FontAwesomeIcon icon={faCommentDots} className='me-2' />Whatsapp</Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  )
}

export default Detailcet