import Head from 'next/head'
import GalleryImage from './galleryImage'

const Gallery = () => {
    const totalImages = 22; // Total number of images

    const generateImageFilenames = (total) => {
        const imageFilenames = [];
        for (let i = 1; i <= total; i++) {
            imageFilenames.push(`${i}.jpeg`);
        }
        return imageFilenames;
    };

    const imageFilenames = generateImageFilenames(totalImages);

    return (
        <>
            <Head>
                <title>Origin Institute</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <div className='container'>
                <section className="py-5">
                    <div className="container my-5">
                        <div className="text-center mb-5">
                            <h2 className="display-5 fw-bolder"><span className="text-gradient d-inline">Unlock your Potential</span></h2>
                            <p className="lead fw-light mb-4">Embark on your journey to success with us.</p>
                        </div>
                        <GalleryImage images={imageFilenames} />
                    </div>
                </section>
            </div>
        </>
    )
}

export default Gallery;