import Head from 'next/head'
import Image from 'next/image';
import One from '../public/galleryImages/1.jpeg'
import two from '../public/galleryImages/2.jpeg'
import three from '../public/galleryImages/3.jpeg'
import four from '../public/galleryImages/4.jpeg'
import five from '../public/galleryImages/5.jpeg'
import six from '../public/galleryImages/6.jpeg'
import seven from '../public/galleryImages/7.jpeg'
import eight from '../public/galleryImages/8.jpeg'
import nine from '../public/galleryImages/9.jpeg'
import ten from '../public/galleryImages/10.jpeg'
import ele from '../public/galleryImages/11.jpeg'
import twe from '../public/galleryImages/12.jpeg'
import thi from '../public/galleryImages/13.jpeg'
import fou from '../public/galleryImages/14.jpeg'
import fiv from '../public/galleryImages/15.jpeg'
import sixt from '../public/galleryImages/16.jpeg'
import sev from '../public/galleryImages/17.jpeg'
import eig from '../public/galleryImages/18.jpeg'
import nin from '../public/galleryImages/19.jpeg'
import twt from '../public/galleryImages/20.jpeg'
import twto from '../public/galleryImages/21.jpeg'
import twtt from '../public/galleryImages/22.jpeg'


const Gallery = () => {
    return (
        <>
            <Head>
                <title>Origin Institute</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <div className='container'>
                <section className="py-5">
                    <div className="container my-5">
                        <div className="text-center mb-5">
                            <h2 className="display-5 fw-bolder"><span className="text-gradient d-inline">Gallery of Unforgettable Moments</span></h2>
                            <p className="lead fw-light mb-4">Capturing the essence of our journey, one cherished memory at a time.</p>
                        </div>
                        <div className="row gx-2 d-flex justify-content-center">
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={One} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={two} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={three} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={four} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={five} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={six} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={seven} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={eight} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={nine} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={ten} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={ele} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={twe} alt="..." />
                                </div>
                            </div><div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={thi} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={fou} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={fiv} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={sixt} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={sev} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={eig} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={nin} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={twt} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={twto} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-3">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3"
                                        src={twtt} alt="..." />
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </>
    )
}

export default Gallery;