import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Demo from '../public/day47-chemistry-lab.png'

const Gallery = () => {
    return (
        <>
            <Head>
                <title>Origin Institute</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <div className='container'>
                <section className="py-5">
                    <div className="container my-5">
                        <div className="text-center mb-5">
                            <h1 className="fw-bolder">Our Work</h1>
                            <p className="lead fw-normal text-muted mb-0">Company portfolio</p>
                        </div>
                        <div className="row gx-3">
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-5">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3" src={Demo} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-5">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3" src={Demo} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative mb-5 mb-lg-0">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3" src={Demo} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3" src={Demo} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3" src={Demo} alt="..." />
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12">
                                <div className="position-relative">
                                    <Image className="img-fluid card-img-top shadow bg-white p-3 rounded-3 mb-3" src={Demo} alt="..." />
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </>
    )
}

export default Gallery;