import Head from 'next/head'
import Link from 'next/link'

import Services from './components/services'
import Achievements from './components/achievements'
import Teams from './components/teams'
import Counselling from './components/counselling'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { library } from "@fortawesome/fontawesome-svg-core";
import { faArrowRight } from "@fortawesome/free-solid-svg-icons";

library.add(faArrowRight);

import styles from '@/styles/Home.module.css'

export default function Home() {
  const handleScroll = (e) => {

    e.preventDefault();

    const href = e.currentTarget.href;
    const targetId = href.replace(/.*\#/, "");

    const elem = document.getElementById(targetId);
    elem?.scrollIntoView({
      behavior: "smooth",
    });
  };

  return (
    <>
      <Head>
        <title>Origin Institute</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={styles.main} >

        {/* Hero Section */}
        <div className={styles.hero}>
          <div className={styles.hero_content}>
            <h1 className={styles.animateHero}>Origin Institute</h1>
            <p className={styles.animateHero}>Where Success Originates.</p>
            <Link href="#srvce" className={`${styles.heroButtons} ${styles.animateHero} me-1`} onClick={handleScroll}  >Get Started <FontAwesomeIcon icon={faArrowRight} className='ms-2' /></Link>
          </div>
        </div>
        {/* Hero section end */}

        {/* <!-- Services Section --> */}
        <Services />
        {/* Services section end */}

        {/* <!-- Carousal section --> */}
        <Achievements />

        {/* Carousel section end */}

        {/* <!-- Team Section --> */}
        <Teams />

        {/* Team Section end */}

        {/* <!-- Counselling section --> */}
        <Counselling />

        {/* <!-- Counselling section  end--> */}
      </main >
    </>
  )
}
